services:
  database:
    container_name: local-pg
    image: postgres:16
    command: -c 'max_connections=200' # -c 'log_statement=all'
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: myapp
    ports:
      - '5438:5432'
