import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SessionWrapper from './ui/SessionProvider';
import { ApolloClientProvider } from './apolloClient';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <ApolloClientProvider>
        <html lang="en">
          <body className={clsx(inter.className, 'bg-slate-700')}>{children}</body>
        </html>
      </ApolloClientProvider>
    </SessionWrapper>
  );
}
